name: J3SPM_AI_cpu
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - pip
  - pytorch=2.4.0
  - torchvision=0.19.0
  - torchaudio=2.4.0
  - cpuonly
  - git
  - pyqt=5
  - labelme
  - pyserial
  - pip:
      - labelImg
