name: J3SPM_AI_gpu
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.11
  - pip
  - pytorch=2.4.0
  - torchvision=0.19.0
  - torchaudio=2.4.0
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  - cudnn
  - git
  - labelme
  - pyserial
  - pyqt=5
  - lxml
